---
title: "PreventTD analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir ="/Users/drewschwartz/Box Sync/02_travelers_diarrhea/04_PreventTD")
#source("/Users/drewschwartz/Box Sync/02_travelers_diarrhea (Blake, Kevin)/04_PreventTD/utilities.R")
```

```{r}
library(ggplot2)
library(vegan)
library(plyr)
library(dplyr)
library(viridis)
library(reshape2)
library(RColorBrewer)
library(multcomp)
library(readr)
library(gtools)
library(lme4)
library(sjPlot)
library(lsmeans)
library(labdsv)
library(cowplot)
library(extrafont)
library(rcompanion)
library(DescTools)
# extrafont::loadfonts()
# extrafont::font_import()

metadata <- read.delim(sep=',',"Metadata/PreventTD_sample_metadata.csv",header=TRUE,stringsAsFactors = F)
metadata$TRT<-metadata$Randomisation
metadata$treatmentvisit<-paste(metadata$Visit,"_",metadata$Randomisation)
metaphlan3alpha<-read.delim(sep='',"data/Metaphlan3/processedDataTables/220415_alphaDiv_metaphlanStandard_species.txt", header=TRUE)
metaphlan3bray<-read.delim(sep='',"data/Metaphlan3/processedDataTables/220415_betaDivLong_metaphlanStandard_species.txt", header=TRUE)
metadataalpha<-join(metadata, metaphlan3alpha, by = "Sample")
metadataalpha<-subset(metadataalpha, Visit!="NA")
metadataalpha$Study<-"PreventTD"

Shortbredlong<-read.delim("data/Shortbred/Data_tables/220421_PreventTDshortbred.txt", header=TRUE)

#Load in TreatTD data too
setwd("/Users/drewschwartz/Box Sync/02_travelers_diarrhea/02_TrEATTD/data/")
dfwideTreat <- read.table("/Users/drewschwartz/Box Sync/02_travelers_diarrhea/02_TrEATTD/data/microbiome/Metaphlan3processedDataTables/210506_wide_metaphlanStandard_species.txt", header = TRUE)
mappingTreat<- read.csv("/Users/drewschwartz/Box Sync/02_travelers_diarrhea/02_TrEATTD/data/archive/Metadata/200708_TreatTDmetadata.csv", header = TRUE)
AlphaTreat<-read.table("/Users/drewschwartz/Box Sync/02_travelers_diarrhea/02_TrEATTD/data/microbiome/Metaphlan3processedDataTables/210506_alphaDiv_metaphlanStandard_species.txt", header = TRUE)
colnames(AlphaTreat)[1]<-"SAMPLE_ID"

colnames(mappingTreat)[2]<-"Visit"
TreatAlphameta<-join(mappingTreat, AlphaTreat)
TreatAlphameta$Post.processed_reads<-TreatAlphameta$r07_READCOUNT
TreatAlphameta$Pre.processed_reads<-TreatAlphameta$r01_READOCUNT

TreatAlphameta$Study<-"TreatTD"
TreatPreventcombinedAlpha<-rbind.fill(metadataalpha, TreatAlphameta)
```

```{r}
#Plot time 0 samples together for Treat and prevent
ggplot(TreatPreventcombinedAlpha, aes(as.factor(Visit), y=richness, color=TRT))+facet_grid(cols = vars(Study)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Richness")+xlab("Visit")+ylab("Number of Species") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()

ggplot(TreatPreventcombinedAlpha, aes(x=Study, y=Post.processed_reads, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Richness")+xlab("Visit")+ylab("Number of Species") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()

pairwise.wilcox.test(TreatPreventcombinedAlpha$Post.processed_reads,TreatPreventcombinedAlpha$Study)
#p<2.8e-07 

#Just baseline samples remove Dups
baselinesamples<-subset(TreatPreventcombinedAlpha, Study=="PreventTD"&Visit=="1"|Study=="TreatTD"&Visit=="0")
baselinesamples$PAIREDFF[is.na(baselinesamples$PAIREDFF)] <-"n"
baselinesamples<-subset(baselinesamples, PAIREDFF=='n')
baselinesamples$COMP_PPX[is.na(baselinesamples$COMP_PPX)] <-"YES"
baselinesamples$DIAR_CLASS[is.na(baselinesamples$DIAR_CLASS)] <-"PREVENT"

ggplot(baselinesamples, aes(as.factor(Visit), y=richness, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Richness")+xlab("Visit")+ylab("Number of Species") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()
ggsave(file="Analysis/220906_Metaphlan3RichnessBaselinePreventTreatTD.pdf")

pairwise.wilcox.test(baselinesamples$richness,baselinesamples$Study)
#p<2e-16 
summary<-aggregate(richness ~ Study,baselinesamples, FUN=median)

ggplot(baselinesamples, aes(as.factor(Visit), y=shannon, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Baseline Diversity")+xlab("Visit")+ylab("Shannon Diversity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()
ggsave(file="Analysis/220906_Metaphlan3ShannonBaselinePreventTreatTD.pdf")

pairwise.wilcox.test(baselinesamples$shannon,baselinesamples$Study)
#p<2e-16 
summary<-aggregate(shannon ~ Study,baselinesamples, FUN=median)
#Prevent TD 3.068619 versus TreatTD 2.016271

ggplot(baselinesamples, aes(as.factor(Visit), y=Post.processed_reads, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Baseline Samples Post Processed Readcount")+xlab("Visit")+ylab("Readcount") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()+scale_y_log10()
ggsave(file="Analysis/220906_PostprocessedreadcountBaselinePreventTreatTD.pdf")

pairwise.wilcox.test(baselinesamples$Post.processed_reads,baselinesamples$Study)
#p<1.7e-05 
summary<-aggregate(Post.processed_reads ~ Study,baselinesamples, FUN=median)
#Average reads Prevent 5779547 vs. Treat 4147954

ggplot(baselinesamples, aes(as.factor(Visit), y=Pre.processed_reads, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Baseline Samples Post Processed Readcount")+xlab("Visit")+ylab("Readcount") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()+scale_y_log10()
ggsave(file="Analysis/220906_PreprocessedreadcountBaselinePreventTreatTD.pdf")

pairwise.wilcox.test(baselinesamples$Pre.processed_reads,baselinesamples$Study)
#p<0.0013
summary<-aggregate(Pre.processed_reads ~ Study,baselinesamples, FUN=median)
#Average reads Prevent 6542813 vs. Treat 4990534

#Baseline samples water only and comp_ppx only
baselinesampleswatercomppx<-subset(baselinesamples, COMP_PPX=="YES"|DIAR_CLASS=="PREVENT")
baselinesampleswatercomppx<-subset(baselinesampleswatercomppx, !DIAR_CLASS=="Acute Dysentery/Fever")

pairwise.wilcox.test(baselinesampleswatercomppx$Post.processed_reads,baselinesampleswatercomppx$Study)
#p<8.6e-06
summary<-aggregate(Post.processed_reads ~ Study,baselinesampleswatercomppx, FUN=median)
#Average reads Prevent 5779547 vs. Treat 4126239

pairwise.wilcox.test(baselinesampleswatercomppx$richness,baselinesampleswatercomppx$Study)
#p<8.3e-16 
summary<-aggregate(richness ~ Study,baselinesampleswatercomppx, FUN=median)
summary<-aggregate(richness ~ Study,baselinesampleswatercomppx, FUN=sd)
#Average Richness Prevent 71 (SD 12.70668) vs. Treat 40 (SD 16.13573)

pairwise.wilcox.test(baselinesampleswatercomppx$shannon,baselinesampleswatercomppx$Study)
#p<2e-16 
summary<-aggregate(shannon ~ Study,baselinesampleswatercomppx, FUN=median)
summary<-aggregate(shannon ~ Study,baselinesampleswatercomppx, FUN=sd)
#Average Shannon Prevent 3.068619 (SD 0.270510) vs. Treat 2.013736 (SD 0.372097)

#Only end point samples
endsamples<-subset(TreatPreventcombinedAlpha, Visit=="2"|Visit=="21")
endsamples$PAIREDFF[is.na(endsamples$PAIREDFF)] <-"n"
endsamples<-subset(endsamples, PAIREDFF=='n')
endsamples$COMP_PPX[is.na(endsamples$COMP_PPX)] <-"YES"
endsamples$DIAR_CLASS[is.na(endsamples$DIAR_CLASS)] <-"PREVENT"

ggplot(endsamples, aes(as.factor(Visit), y=richness, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Richness")+xlab("Visit")+ylab("Number of Species") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()+scale_x_discrete(limits=c("21","2"))+theme_pub()
ggsave(file="Analysis/220906_Metaphlan3RichnessEndsamplesPreventTreatTD.pdf")

ggplot(endsamples, aes(as.factor(Visit), y=shannon, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("End of study diversity")+xlab("Visit")+ylab("Shannon Diversity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()+scale_x_discrete(limits=c("21","2"))+theme_pub()
ggsave(file="Analysis/220906_Metaphlan3ShannonEndstudyPreventTreatTD.pdf")

pairwise.wilcox.test(endsamples$shannon,endsamples$Study)
#p<2e-16 
summary<-aggregate(shannon ~ Study,endsamples, FUN=median)
#Prevent TD 3.017541 versus TreatTD 2.263863

ggplot(endsamples, aes(as.factor(Visit), y=Post.processed_reads, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("End of Study Post Processed Readcount")+xlab("Visit")+ylab("Read count") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()+scale_y_log10()+scale_x_discrete(limits=c("21","2"))+theme_pub()
ggsave(file="Analysis/220906_PostprocessedreadcountEndsamplePreventTreatTD.pdf")

pairwise.wilcox.test(endsamples$Post.processed_reads,endsamples$Study)
#0.17
summary<-aggregate(Post.processed_reads ~ Study,endsamples, FUN=median)
#Average reads Prevent 4802573 vs. Treat 4300739

ggplot(endsamples, aes(as.factor(Visit), y=Pre.processed_reads, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("End of Study Pre Processed Readcount")+xlab("Visit")+ylab("Readcount") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()+scale_y_log10()+scale_x_discrete(limits=c("21","2"))+theme_pub()
ggsave(file="Analysis/220906_PreprocessedreadcountEndsamplePreventTreatTD.pdf")

pairwise.wilcox.test(endsamples$Pre.processed_reads,baselinesamples$Study)
#0.19
summary<-aggregate(Pre.processed_reads ~ Study,endsamples, FUN=median)
#Average reads Prevent 5454375 vs. Treat 5009572

#End timepoint samples water only and comp_ppx only
endsampleswatercomppx<-subset(endsamples, COMP_PPX=="YES")
endsampleswatercomppx<-subset(endsampleswatercomppx, !DIAR_CLASS=="Acute Dysentery/Fever")

pairwise.wilcox.test(endsampleswatercomppx$Post.processed_reads,endsampleswatercomppx$Study)
#p=0.048 
summary<-aggregate(Post.processed_reads ~ Study,endsampleswatercomppx, FUN=median)
#Average reads Prevent 4809213 vs. Treat 4267752

pairwise.wilcox.test(endsampleswatercomppx$richness,endsampleswatercomppx$Study)
#p<9.9e-15 
summary<-aggregate(richness ~ Study,endsampleswatercomppx, FUN=median)
summary<-aggregate(richness ~ Study,endsampleswatercomppx, FUN=sd)
#Average Richness Prevent 65.0 (SD 12.28690) vs. Treat 39.5 (SD 12.89838)

pairwise.wilcox.test(endsampleswatercomppx$shannon,endsampleswatercomppx$Study)
#p<2e-16 
summary<-aggregate(shannon ~ Study,endsampleswatercomppx, FUN=median)
summary<-aggregate(shannon ~ Study,endsampleswatercomppx, FUN=sd)
#Average Shannon Prevent 3.006279 (SD 0.2511659) vs. Treat 2.223891 (SD 0.3009556)


```


```{r}
#Richness over time metaphlan3 by treatment
ggplot(metadataalpha, aes(as.factor(Visit), y=richness, color=Randomisation)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Richness")+xlab("Visit")+ylab("Number of Species") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00"))+theme_pub()
ggsave(file="Analysis/220418_Metaphlan3Richnessbyvisit.pdf")

#Shannon over time metaphlan3 by treatment
ggplot(metadataalpha, aes(as.factor(Visit), y=shannon, color=Randomisation)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Shannon Diversity")+xlab("Visit")+ylab("Shannon Diversity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00"))+theme_pub()
ggsave(file="Analysis/220418_Metaphlan3Shannonbyvisit.pdf")

#linear mixed effect model
fitrich<- lmer(richness~treatmentvisit+ (1|studyid), data=metadataalpha)
anova(fitrich)
Tukrich<-lsmeans(fitrich, pairwise~treatmentvisit, adjust="tukey")
Tukrich
# treatmentvisit                   lsmean   SE  df lower.CL upper.CL
# 1 _ Placebo                        74.1 2.11 194     69.9     78.2
# 1 _ Rifaximin 550 mg daily         69.4 1.84 194     65.8     73.0
# 1 _ Rifaximin 550 mg twice a day   71.4 1.97 194     67.5     75.3
# 2 _ Placebo                        68.5 2.11 194     64.3     72.6
# 2 _ Rifaximin 550 mg daily         64.7 1.84 194     61.1     68.3
# 2 _ Rifaximin 550 mg twice a day   64.3 1.97 194     60.4     68.2

#Degrees-of-freedom method: kenward-roger 
#Confidence level used: 0.95 
# contrast                                                            estimate   SE  df t.ratio p.value
# 1 _ Placebo - 1 _ Rifaximin 550 mg daily                               4.694 2.79 194   1.680  0.5465
# 1 _ Placebo - 1 _ Rifaximin 550 mg twice a day                         2.711 2.88 194   0.940  0.9355
# 1 _ Placebo - 2 _ Placebo                                              5.629 2.18 118   2.578  0.1109
# 1 _ Placebo - 2 _ Rifaximin 550 mg daily                               9.368 2.79 194   3.353  0.0122
# 1 _ Placebo - 2 _ Rifaximin 550 mg twice a day                         9.786 2.88 194   3.394  0.0107
# 1 _ Rifaximin 550 mg daily - 1 _ Rifaximin 550 mg twice a day         -1.984 2.69 194  -0.737  0.9771
# 1 _ Rifaximin 550 mg daily - 2 _ Placebo                               0.934 2.79 194   0.334  0.9994
# 1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg daily                4.674 1.90 118   2.454  0.1466
# 1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day          5.091 2.69 194   1.891  0.4110
# 1 _ Rifaximin 550 mg twice a day - 2 _ Placebo                         2.918 2.88 194   1.012  0.9135
# 1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg daily          6.658 2.69 194   2.472  0.1375
# 1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg twice a day    7.075 2.04 118   3.464  0.0095
# 2 _ Placebo - 2 _ Rifaximin 550 mg daily                               3.740 2.79 194   1.339  0.7631
# 2 _ Placebo - 2 _ Rifaximin 550 mg twice a day                         4.157 2.88 194   1.442  0.7013
# 2 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day          0.417 2.69 194   0.155  1.0000

fitshann<- lmer(shannon~treatmentvisit+ (1|studyid), data=metadataalpha)
anova(fitshann)
Tukshannon<-lsmeans(fitshann, pairwise~treatmentvisit, adjust="tukey")
Tukshannon
# treatmentvisit                   lsmean     SE  df lower.CL upper.CL
# 1 _ Placebo                        3.08 0.0439 213     2.99     3.16
# 1 _ Rifaximin 550 mg daily         2.98 0.0383 213     2.90     3.05
# 1 _ Rifaximin 550 mg twice a day   3.04 0.0411 213     2.96     3.12
# 2 _ Placebo                        3.00 0.0439 213     2.91     3.08
# 2 _ Rifaximin 550 mg daily         3.02 0.0383 213     2.94     3.10
# 2 _ Rifaximin 550 mg twice a day   3.00 0.0411 213     2.92     3.08

#Degrees-of-freedom method: kenward-roger 
#Confidence level used: 0.95 
# contrast                                                            estimate     SE  df t.ratio p.value
# 1 _ Placebo - 1 _ Rifaximin 550 mg daily                             0.10020 0.0583 213   1.719  0.5211
# 1 _ Placebo - 1 _ Rifaximin 550 mg twice a day                       0.03390 0.0602 213   0.563  0.9932
# 1 _ Placebo - 2 _ Placebo                                            0.08091 0.0508 118   1.591  0.6058
# 1 _ Placebo - 2 _ Rifaximin 550 mg daily                             0.05668 0.0583 213   0.972  0.9263
# 1 _ Placebo - 2 _ Rifaximin 550 mg twice a day                       0.07702 0.0602 213   1.280  0.7956
# 1 _ Rifaximin 550 mg daily - 1 _ Rifaximin 550 mg twice a day       -0.06630 0.0562 213  -1.180  0.8461
# 1 _ Rifaximin 550 mg daily - 2 _ Placebo                            -0.01929 0.0583 213  -0.331  0.9995
# 1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg daily             -0.04351 0.0443 118  -0.981  0.9231
# 1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day       -0.02318 0.0562 213  -0.412  0.9985
# 1 _ Rifaximin 550 mg twice a day - 2 _ Placebo                       0.04701 0.0602 213   0.781  0.9704
# 1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg daily        0.02279 0.0562 213   0.406  0.9986
# 1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg twice a day  0.04313 0.0476 118   0.907  0.9441
# 2 _ Placebo - 2 _ Rifaximin 550 mg daily                            -0.02422 0.0583 213  -0.415  0.9984
# 2 _ Placebo - 2 _ Rifaximin 550 mg twice a day                      -0.00388 0.0602 213  -0.065  1.0000
# 2 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day        0.02034 0.0562 213   0.362  0.9992

#ssummary statistics for PreventTD
summaryPreventmicrobiome<-aggregate(richness ~ treatmentvisit,metadataalpha, FUN=median)

#Now to remove those who didnt take their medication
metadataalphacomplete<-subset(metadataalpha, COMP_PPX!='NO')
summaryPreventmicrobiome<-aggregate(richness ~ treatmentvisit,metadataalphacomplete, FUN=median)
summaryPreventmicrobiome<-aggregate(shannon ~ treatmentvisit,metadataalphacomplete, FUN=median)

write.csv(metadataalphacomplete, "Analysis/230424_PreventTDAlphadivcompletedppx.csv")

#Richness over time metaphlan3 by treatment
ggplot(metadataalphacomplete, aes(as.factor(Visit), y=richness, color=Randomisation)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Richness")+xlab("Visit")+ylab("Number of Species") + scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00"))+theme_pub()
ggsave(file="Analysis/230414_Metaphlan3Richnessbyvisitcompletedonly.pdf", height=2, width=4)

#Shannon over time metaphlan3 by treatment
ggplot(metadataalphacomplete, aes(as.factor(Visit), y=shannon, color=Randomisation)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Shannon Diversity")+xlab("Visit")+ylab("Shannon Diversity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00"))+theme_pub()
ggsave(file="Analysis/230414_Metaphlan3Shannonbyvisitcompletedonly.pdf", height=2, width=4)

fitrichcomplete<- lmer(richness~treatmentvisit+ (1|studyid), data=metadataalphacomplete)
anova(fitrichcomplete)
Tukrichcomplete<-lsmeans(fitrichcomplete, pairwise~treatmentvisit, adjust="tukey")
Tukrichcomplete
#treatmentvisit                   lsmean   SE  df lower.CL upper.CL
# 1 _ Placebo                        72.9 2.16 188     68.7     77.2
# 1 _ Rifaximin 550 mg daily         69.7 1.87 188     66.0     73.4
# 1 _ Rifaximin 550 mg twice a day   71.3 1.98 188     67.4     75.2
# 2 _ Placebo                        67.9 2.16 188     63.6     72.1
# 2 _ Rifaximin 550 mg daily         64.8 1.87 188     61.1     68.5
# 2 _ Rifaximin 550 mg twice a day   64.6 1.98 188     60.7     68.6

#Degrees-of-freedom method: kenward-roger 
#Confidence level used: 0.95 

# contrast                                                            estimate   SE  df t.ratio p.value
# 1 _ Placebo - 1 _ Rifaximin 550 mg daily                               3.258 2.85 188   1.142  0.8633
# 1 _ Placebo - 1 _ Rifaximin 550 mg twice a day                         1.632 2.93 188   0.557  0.9936
# 1 _ Placebo - 2 _ Placebo                                              5.061 2.26 113   2.238  0.2290
# 1 _ Placebo - 2 _ Rifaximin 550 mg daily                               8.144 2.85 188   2.854  0.0535
# 1 _ Placebo - 2 _ Rifaximin 550 mg twice a day                         8.298 2.93 188   2.832  0.0568
# 1 _ Rifaximin 550 mg daily - 1 _ Rifaximin 550 mg twice a day         -1.626 2.72 188  -0.597  0.9912
# 1 _ Rifaximin 550 mg daily - 2 _ Placebo                               1.803 2.85 188   0.632  0.9885
# 1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg daily                4.886 1.96 113   2.495  0.1344
# 1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day          5.041 2.72 188   1.850  0.4365
# 1 _ Rifaximin 550 mg twice a day - 2 _ Placebo                         3.429 2.93 188   1.170  0.8505
# 1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg daily          6.512 2.72 188   2.390  0.1651
# 1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg twice a day    6.667 2.08 113   3.205  0.0212
# 2 _ Placebo - 2 _ Rifaximin 550 mg daily                               3.083 2.85 188   1.081  0.8886
# 2 _ Placebo - 2 _ Rifaximin 550 mg twice a day                         3.238 2.93 188   1.105  0.8789
# 2 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day          0.154 2.72 188   0.057  1.0000

#Degrees-of-freedom method: kenward-roger 
#P value adjustment: tukey method for comparing a family of 6 estimates 

fitshanncomplete<- lmer(shannon~treatmentvisit+ (1|studyid), data=metadataalphacomplete)
anova(fitshanncomplete)
Tukshannoncomplete<-lsmeans(fitshanncomplete, pairwise~treatmentvisit, adjust="tukey")
Tukshannoncomplete

# 1 _ Placebo                        3.06 0.0457 204     2.97     3.15
# 1 _ Rifaximin 550 mg daily         2.98 0.0396 204     2.90     3.05
# 1 _ Rifaximin 550 mg twice a day   3.05 0.0421 204     2.96     3.13
# 2 _ Placebo                        2.99 0.0457 204     2.90     3.08
# 2 _ Rifaximin 550 mg daily         3.01 0.0396 204     2.93     3.09
# 2 _ Rifaximin 550 mg twice a day   3.00 0.0421 204     2.91     3.08

# Degrees-of-freedom method: kenward-roger 
# Confidence level used: 0.95 
# contrast                                                            estimate     SE  df t.ratio p.value
# 1 _ Placebo - 1 _ Rifaximin 550 mg daily                             0.08488 0.0605 204   1.403  0.7255
# 1 _ Placebo - 1 _ Rifaximin 550 mg twice a day                       0.01323 0.0622 204   0.213  0.9999
# 1 _ Placebo - 2 _ Placebo                                            0.07562 0.0530 113   1.427  0.7103
# 1 _ Placebo - 2 _ Rifaximin 550 mg daily                             0.04921 0.0605 204   0.813  0.9649
# 1 _ Placebo - 2 _ Rifaximin 550 mg twice a day                       0.06519 0.0622 204   1.049  0.9007
# 1 _ Rifaximin 550 mg daily - 1 _ Rifaximin 550 mg twice a day       -0.07166 0.0578 204  -1.240  0.8167
# 1 _ Rifaximin 550 mg daily - 2 _ Placebo                            -0.00926 0.0605 204  -0.153  1.0000
# 1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg daily             -0.03567 0.0459 113  -0.777  0.9708
# 1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day       -0.01970 0.0578 204  -0.341  0.9994
# 1 _ Rifaximin 550 mg twice a day - 2 _ Placebo                       0.06240 0.0622 204   1.004  0.9163
# 1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg daily        0.03599 0.0578 204   0.623  0.9893
# 1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg twice a day  0.05196 0.0487 113   1.066  0.8937
# 2 _ Placebo - 2 _ Rifaximin 550 mg daily                            -0.02641 0.0605 204  -0.436  0.9980
# 2 _ Placebo - 2 _ Rifaximin 550 mg twice a day                      -0.01044 0.0622 204  -0.168  1.0000
# 2 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day        0.01597 0.0578 204   0.276  0.9998

# Degrees-of-freedom method: kenward-roger 
# P value adjustment: tukey method for comparing a family of 6 estimates
```
```{r}
#Beta diversity plotting
sameIDbeta<-subset(metaphlan3bray, samp1_ID==samp2_ID)
sameIDbeta<-subset(sameIDbeta, !samp1==samp2)
sameIDbeta$Sample<-sameIDbeta$samp2
sameIDbetameta<-join(sameIDbeta, metadata, by = "Sample")
sameIDbetameta<-subset(sameIDbetameta, COMP_PPX!='NO')

#Plot beta diversity Bray curtis of traveler by treatment condition
ggplot(sameIDbetameta, aes(x=Randomisation, y=dist, color=Randomisation)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Bray Curtis ")+xlab("Treatment")+ylab("distance") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00"))+theme_pub()
ggsave(file="Analysis/220419_Metaphlan3betadistanceselfV1toV2.pdf")

pairwise.wilcox.test(sameIDbetameta$dist, sameIDbetameta$Randomisation, p.adjust.method = "BH")

#                             Placebo Rifaximin 550 mg daily
#Rifaximin 550 mg daily       0.89    -                     
#Rifaximin 550 mg twice a day 0.89    0.89                  
#P value adjustment method: BH 
```
```{r}
#create wide shortbred table for RPKM data
# Shortbredwide<-Shortbredlong[-c(4:20)]
# Shortbredwide<-reshape(Shortbredwide, idvar="Sample", timevar = "Family", direction ="wide")
# Shortbredwide[is.na(Shortbredwide)] <- 0
# rownames(Shortbredwide)=Shortbredwide$Sample
# Shortbredwide$Sample=NULL
# Shortbredwide$Sum<-rowSums(Shortbredwide)
# Shortbredwide$Sample<-row.names(Shortbredwide)
#write.csv(Shortbredwide,"data/Shortbred/Data_tables/200421_ShortbredwideCount.csv")
Shortbredwide<-read.csv("data/Shortbred/Data_tables/200421_ShortbredwideCount.csv")
Shortbredmetadata<-join(Shortbredwide, metadata, by ="Sample")


ggplot(Shortbredmetadata, aes(as.factor(Visit), y=Sum, color=Randomisation)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Antibiotic Resistance Genes")+xlab("Visit")+ylab("Sum RPKM ARGs") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00"))+theme_pub()
ggsave(file="Analysis/230413_ShortbredARGsSUM.pdf", height=2, width=4)

#Linear mixed effect model
fitARG<- lmer(Sum~treatmentvisit+ (1|studyid), data=Shortbredmetadata)
anova(fitARG)
TukfitARG<-lsmeans(fitARG, pairwise~treatmentvisit, adjust="tukey")
TukfitARG
#  treatmentvisit                   lsmean  SE  df lower.CL upper.CL
#  1 _ Placebo                        5203 308 162     4595     5812
#  1 _ Rifaximin 550 mg daily         5426 269 162     4895     5957
#  1 _ Rifaximin 550 mg twice a day   5283 288 162     4714     5852
#  2 _ Placebo                        5803 308 162     5194     6411
#  2 _ Rifaximin 550 mg daily         5593 269 162     5062     6124
#  2 _ Rifaximin 550 mg twice a day   5960 288 162     5391     6529
# 
# Degrees-of-freedom method: kenward-roger 
# Confidence level used: 0.95 
# 
# $contrasts
#  contrast                                                            estimate  SE  df t.ratio p.value
#  1 _ Placebo - 1 _ Rifaximin 550 mg daily                              -222.9 409 162  -0.545  0.9942
#  1 _ Placebo - 1 _ Rifaximin 550 mg twice a day                         -79.6 422 162  -0.189  1.0000
#  1 _ Placebo - 2 _ Placebo                                             -599.3 247 118  -2.422  0.1571
#  1 _ Placebo - 2 _ Rifaximin 550 mg daily                              -389.7 409 162  -0.953  0.9317
#  1 _ Placebo - 2 _ Rifaximin 550 mg twice a day                        -756.4 422 162  -1.793  0.4732
#  1 _ Rifaximin 550 mg daily - 1 _ Rifaximin 550 mg twice a day          143.3 394 162   0.364  0.9992
#  1 _ Rifaximin 550 mg daily - 2 _ Placebo                              -376.4 409 162  -0.921  0.9407
#  1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg daily               -166.9 216 118  -0.773  0.9715
#  1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day         -533.5 394 162  -1.354  0.7542
#  1 _ Rifaximin 550 mg twice a day - 2 _ Placebo                        -519.7 422 162  -1.232  0.8206
#  1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg daily         -310.2 394 162  -0.787  0.9694
#  1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg twice a day   -676.8 231 118  -2.925  0.0465
#  2 _ Placebo - 2 _ Rifaximin 550 mg daily                               209.5 409 162   0.513  0.9956
#  2 _ Placebo - 2 _ Rifaximin 550 mg twice a day                        -157.1 422 162  -0.372  0.9991
#  2 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day         -366.7 394 162  -0.930  0.9381

#Now just those who completed therapy
Shortbredmetadatacomp<-subset(Shortbredmetadata, COMP_PPX=="YES")
write.csv(Shortbredmetadatacomp, "Analysis/230424_PreventTDShortbredcompletedppx.csv")

ggplot(Shortbredmetadatacomp, aes(as.factor(Visit), y=Sum, color=Randomisation)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Antibiotic Resistance Genes")+xlab("Visit")+ylab("Sum RPKM ARGs") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00"))+theme_pub()
ggsave(file="Analysis/230413_ShortbredARGsSUMCOMPPPX.pdf", height=2, width=4)

#Linear mixed effect model
fitARGcomp<- lmer(Sum~treatmentvisit+ (1|studyid), data=Shortbredmetadatacomp)
anova(fitARGcomp)
TukfitARGcomp<-lsmeans(fitARGcomp, pairwise~treatmentvisit, adjust="tukey")
TukfitARGcomp
# treatmentvisit                   lsmean  SE  df lower.CL upper.CL
#  1 _ Placebo                        5224 308 155     4615     5833
#  1 _ Rifaximin 550 mg daily         5390 267 155     4863     5918
#  1 _ Rifaximin 550 mg twice a day   5134 284 155     4574     5695
#  2 _ Placebo                        5836 308 155     5227     6445
#  2 _ Rifaximin 550 mg daily         5655 267 155     5127     6182
#  2 _ Rifaximin 550 mg twice a day   5833 284 155     5273     6394
# 
# Degrees-of-freedom method: kenward-roger 
# Confidence level used: 0.95 
# 
# $contrasts
#  contrast                                                            estimate  SE  df t.ratio p.value
#  1 _ Placebo - 1 _ Rifaximin 550 mg daily                              -166.2 408 155  -0.407  0.9985
#  1 _ Placebo - 1 _ Rifaximin 550 mg twice a day                          89.8 419 155   0.214  0.9999
#  1 _ Placebo - 2 _ Placebo                                             -612.1 249 113  -2.463  0.1441
#  1 _ Placebo - 2 _ Rifaximin 550 mg daily                              -430.6 408 155  -1.056  0.8979
#  1 _ Placebo - 2 _ Rifaximin 550 mg twice a day                        -609.2 419 155  -1.454  0.6937
#  1 _ Rifaximin 550 mg daily - 1 _ Rifaximin 550 mg twice a day          256.0 390 155   0.657  0.9862
#  1 _ Rifaximin 550 mg daily - 2 _ Placebo                              -445.9 408 155  -1.093  0.8834
#  1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg daily               -264.4 215 113  -1.228  0.8221
#  1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day         -443.0 390 155  -1.137  0.8650
#  1 _ Rifaximin 550 mg twice a day - 2 _ Placebo                        -702.0 419 155  -1.676  0.5499
#  1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg daily         -520.4 390 155  -1.336  0.7645
#  1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg twice a day   -699.1 229 113  -3.058  0.0324
#  2 _ Placebo - 2 _ Rifaximin 550 mg daily                               181.6 408 155   0.445  0.9978
#  2 _ Placebo - 2 _ Rifaximin 550 mg twice a day                           2.9 419 155   0.007  1.0000
#  2 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day         -178.7 390 155  -0.459  0.9974

SummaryPreventshortbredARGs<-aggregate(Sum ~ treatmentvisit,Shortbredmetadata, FUN=median)

ggplot(Shortbredmetadata, aes(as.factor(Visit), y=Count, color=Randomisation)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Antibiotic Resistance Genes")+xlab("Visit")+ylab("Sum RPKM ARGs") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00"))+theme_pub()
ggsave(file="Analysis/220823_ShortbredARGsCount.pdf", height=2, width=4)

#Linear mixed effect model
fitARGcount<- lmer(Count~treatmentvisit+ (1|studyid), data=Shortbredmetadata)
anova(fitARGcount)
TukfitARGcount<-lsmeans(fitARGcount, pairwise~treatmentvisit, adjust="tukey")
TukfitARGcount
#  treatmentvisit                   lsmean    SE  df lower.CL upper.CL
#  1 _ Placebo                         268 11.23 213      246      290
#  1 _ Rifaximin 550 mg daily          241  9.79 213      222      260
#  1 _ Rifaximin 550 mg twice a day    252 10.50 213      231      273
#  2 _ Placebo                         282 11.23 213      260      304
#  2 _ Rifaximin 550 mg daily          245  9.79 213      225      264
#  2 _ Rifaximin 550 mg twice a day    242 10.50 213      221      263
# 
# Degrees-of-freedom method: kenward-roger 
# Confidence level used: 0.95 
# 
# $contrasts
#  contrast                                                            estimate   SE  df t.ratio p.value
#  1 _ Placebo - 1 _ Rifaximin 550 mg daily                               27.00 14.9 213   1.812  0.4600
#  1 _ Placebo - 1 _ Rifaximin 550 mg twice a day                         15.74 15.4 213   1.024  0.9096
#  1 _ Placebo - 2 _ Placebo                                             -13.77 13.0 118  -1.057  0.8973
#  1 _ Placebo - 2 _ Rifaximin 550 mg daily                               23.39 14.9 213   1.570  0.6191
#  1 _ Placebo - 2 _ Rifaximin 550 mg twice a day                         25.96 15.4 213   1.689  0.5406
#  1 _ Rifaximin 550 mg daily - 1 _ Rifaximin 550 mg twice a day         -11.26 14.4 213  -0.784  0.9700
#  1 _ Rifaximin 550 mg daily - 2 _ Placebo                              -40.77 14.9 213  -2.737  0.0723
#  1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg daily                -3.61 11.4 118  -0.317  0.9996
#  1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day          -1.04 14.4 213  -0.072  1.0000
#  1 _ Rifaximin 550 mg twice a day - 2 _ Placebo                        -29.51 15.4 213  -1.920  0.3931
#  1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg daily           7.65 14.4 213   0.533  0.9948
#  1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg twice a day    10.22 12.2 118   0.839  0.9596
#  2 _ Placebo - 2 _ Rifaximin 550 mg daily                               37.16 14.9 213   2.495  0.1303
#  2 _ Placebo - 2 _ Rifaximin 550 mg twice a day                         39.74 15.4 213   2.585  0.1055
#  2 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day           2.57 14.4 213   0.179  1.0000

ggplot(Shortbredmetadatacomp, aes(as.factor(Visit), y=Count, color=Randomisation)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Antibiotic Resistance Genes")+xlab("Visit")+ylab("Sum RPKM ARGs") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00"))+theme_pub()
ggsave(file="Analysis/230413_ShortbredARGsCountCOMPPPX.pdf", height=2, width=4)

fitARGcompcount<- lmer(Count~treatmentvisit+ (1|studyid), data=Shortbredmetadatacomp)
anova(fitARGcompcount)
TukfitARGcompcount<-lsmeans(fitARGcompcount, pairwise~treatmentvisit, adjust="tukey")
TukfitARGcompcount
#  1 _ Placebo                         265 11.47 202      242      287
#  1 _ Rifaximin 550 mg daily          241  9.93 202      221      260
#  1 _ Rifaximin 550 mg twice a day    251 10.55 202      230      272
#  2 _ Placebo                         281 11.47 202      259      304
#  2 _ Rifaximin 550 mg daily          246  9.93 202      226      265
#  2 _ Rifaximin 550 mg twice a day    245 10.55 202      224      266
# 
# Degrees-of-freedom method: kenward-roger 
# Confidence level used: 0.95 
# 
# $contrasts
#  contrast                                                            estimate   SE  df t.ratio p.value
#  1 _ Placebo - 1 _ Rifaximin 550 mg daily                              23.788 15.2 202   1.568  0.6208
#  1 _ Placebo - 1 _ Rifaximin 550 mg twice a day                        13.862 15.6 202   0.889  0.9487
#  1 _ Placebo - 2 _ Placebo                                            -16.758 13.2 113  -1.272  0.7995
#  1 _ Placebo - 2 _ Rifaximin 550 mg daily                              18.833 15.2 202   1.241  0.8161
#  1 _ Placebo - 2 _ Rifaximin 550 mg twice a day                        19.786 15.6 202   1.269  0.8013
#  1 _ Rifaximin 550 mg daily - 1 _ Rifaximin 550 mg twice a day         -9.925 14.5 202  -0.685  0.9835
#  1 _ Rifaximin 550 mg daily - 2 _ Placebo                             -40.545 15.2 202  -2.672  0.0855
#  1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg daily               -4.955 11.4 113  -0.434  0.9980
#  1 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day         -4.002 14.5 202  -0.276  0.9998
#  1 _ Rifaximin 550 mg twice a day - 2 _ Placebo                       -30.620 15.6 202  -1.965  0.3664
#  1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg daily          4.971 14.5 202   0.343  0.9994
#  1 _ Rifaximin 550 mg twice a day - 2 _ Rifaximin 550 mg twice a day    5.923 12.1 113   0.489  0.9965
#  2 _ Placebo - 2 _ Rifaximin 550 mg daily                              35.591 15.2 202   2.345  0.1810
#  2 _ Placebo - 2 _ Rifaximin 550 mg twice a day                        36.543 15.6 202   2.345  0.1813
#  2 _ Rifaximin 550 mg daily - 2 _ Rifaximin 550 mg twice a day          0.952 14.5 202   0.066  1.0000
```

```{r}

TreatShortbredwide<-read.csv("~/Box Sync/02_travelers_diarrhea/02_TrEATTD/data/resistome/220530_ShortbredwideCount.csv")
mappingTreat$Sample<-mappingTreat$SAMPLE_ID
TreatShortbredmetadata<-join(TreatShortbredwide, mappingTreat, by ="Sample")
TreatShortbredmetadata$Study<-"TreatTD"

#adding prevent designation to Prevent TD metadata
Shortbredmetadata$Study<-"PreventTD"
Shortbredmetadatacomp$Study<-"PreventTD"
TreatPreventcombinedShortbread<-rbind.fill(TreatShortbredmetadata, Shortbredmetadata)

baselineresistance<-subset(TreatPreventcombinedShortbread, Study=="PreventTD"&Visit=="1"|Study=="TreatTD"&Visit=="0")
baselineresistance$PAIREDFF[is.na(baselineresistance$PAIREDFF)] <-"n"
baselineresistance<-subset(baselineresistance, PAIREDFF=='n')

ggplot(baselineresistance, aes(as.factor(Visit), y=Sum, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Baseline resistance")+xlab("Visit")+ylab("ARG RPKM SUM") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()+scale_y_log10()
ggsave(file="Analysis/230413_ShortbredSumBaselinePreventTreatTDcompletedppx.pdf", height=2, width=4)

pairwise.wilcox.test(baselineresistance$Sum,baselinesamples$Study)
#p=0.12

ggplot(baselineresistance, aes(as.factor(Visit), y=Count, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Baseline resistance count")+xlab("Visit")+ylab("Unique ARG count") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()+scale_y_log10()
ggsave(file="Analysis/230413_ShortbredCountBaselinePreventTreatTD.pdf", height=2, width=4)

pairwise.wilcox.test(baselineresistance$Count,baselinesamples$Study)
#p=0.38

#Only end point samples in those who completed PPX
TreatPreventcombinedShortbreadcompleted<-rbind.fill(TreatShortbredmetadata, Shortbredmetadatacomp)
endresistance<-subset(TreatPreventcombinedShortbreadcompleted, Visit=="2"|Visit=="21")
endresistance$PAIREDFF[is.na(endresistance$PAIREDFF)] <-"n"
endresistance<-subset(endresistance, PAIREDFF=='n')

ggplot(endresistance, aes(as.factor(Visit), y=Sum, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("End of study resistance")+xlab("Visit")+ylab("ARG RPKM SUM") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()+scale_x_discrete(limits=c("21","2"))+theme_pub()
ggsave(file="Analysis/230413_ShortbredSumEndstudyPreventTreatTD.pdf", height=2, width=4)

pairwise.wilcox.test(endresistance$Sum,endresistance$Study)
#p=1.3e-11 

ggplot(endresistance, aes(as.factor(Visit), y=Count, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("End of study resistance count")+xlab("Visit")+ylab("Unique ARG count") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4", "PLA" = "#AF2B30", "LOP" = "#CF5D42"))+theme_pub()+scale_y_log10()+scale_x_discrete(limits=c("21","2"))+theme_pub()
ggsave(file="Analysis/230413_ShortbredCountendstudyPreventTreatTD.pdf", height=2, width=4)

pairwise.wilcox.test(endresistance$Count,endresistance$Study)
#p=2.3e-14

#Now to remove the Lop and Pla groups and plot alpha diversity of TreatTD and both cohorts together
TreatAlphametanofever<-subset(TreatAlphameta, TRT!='LOP' & TRT!='PLA')
#remove dups
TreatAlphametanofever<-subset(TreatAlphametanofever, PAIREDFF=='n')

ggplot(TreatAlphametanofever, aes(as.factor(Visit), y=richness, color=TRT))+facet_grid(cols = vars(Study)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Richness")+xlab("Visit")+ylab("Number of Species") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4"))+theme_pub()
ggsave(file="Analysis/230413_TreatTDRichnessonlywater.pdf", height=2, width=4)

ggplot(TreatAlphametanofever, aes(as.factor(Visit), y=shannon, color=TRT))+facet_grid(cols = vars(Study)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Shannon Diversity")+xlab("Visit")+ylab("Shannon Diversity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4"))+theme_pub()
ggsave(file="Analysis/230413_TreatTDShannononlywater.pdf", height=2, width=4)

#linear mixed effect model
TreatAlphametanofever$treatmentvisit<-paste(TreatAlphametanofever$TRT,TreatAlphametanofever$Visit)
fitrichtreat<- lmer(richness~treatmentvisit+ (1|STUDY_ID), data=TreatAlphametanofever)
anova(fitrichtreat)
#                npar Sum Sq Mean Sq F value
# treatmentvisit    8 460.98  57.623  0.6343
Tukrichtreat<-lsmeans(fitrichtreat, pairwise~treatmentvisit, adjust="tukey")
Tukrichtreat
# AZI 0 - AZI 21   -0.1667 3.18 113.2  -0.052  1.0000
#  AZI 0 - AZI 7     4.7509 3.29 113.5   1.444  0.8779
#  AZI 0 - LEV 0    -1.3868 5.11  57.0  -0.272  1.0000
#  AZI 0 - LEV 21   -1.4012 5.15  58.4  -0.272  1.0000
#  AZI 0 - LEV 7    -4.4550 5.15  58.4  -0.865  0.9939
#  AZI 0 - RIF 0     1.1791 5.34  59.0   0.221  1.0000
#  AZI 0 - RIF 21    0.8791 5.27  56.5   0.167  1.0000
#  AZI 0 - RIF 7     1.6438 5.27  56.5   0.312  1.0000
#  AZI 21 - AZI 7    4.9176 3.29 113.5   1.495  0.8556
#  AZI 21 - LEV 0   -1.2201 5.11  57.0  -0.239  1.0000
#  AZI 21 - LEV 21  -1.2346 5.15  58.4  -0.240  1.0000
#  AZI 21 - LEV 7   -4.2884 5.15  58.4  -0.833  0.9953
#  AZI 21 - RIF 0    1.3458 5.34  59.0   0.252  1.0000
#  AZI 21 - RIF 21   1.0458 5.27  56.5   0.198  1.0000
#  AZI 21 - RIF 7    1.8105 5.27  56.5   0.343  1.0000
#  AZI 7 - LEV 0    -6.1376 5.17  59.5  -1.187  0.9561
#  AZI 7 - LEV 21   -6.1521 5.21  60.9  -1.181  0.9576
#  AZI 7 - LEV 7    -9.2059 5.21  60.9  -1.767  0.7031
#  AZI 7 - RIF 0    -3.5718 5.40  61.3  -0.662  0.9991
#  AZI 7 - RIF 21   -3.8718 5.34  58.8  -0.726  0.9982
#  AZI 7 - RIF 7    -3.1071 5.34  58.8  -0.582  0.9996
#  LEV 0 - LEV 21   -0.0145 3.17 114.4  -0.005  1.0000
#  LEV 0 - LEV 7    -3.0683 3.17 114.4  -0.969  0.9879
#  LEV 0 - RIF 0     2.5658 5.13  63.0   0.500  0.9999
#  LEV 0 - RIF 21    2.2659 5.06  60.2   0.447  1.0000
#  LEV 0 - RIF 7     3.0306 5.06  60.2   0.598  0.9996
#  LEV 21 - LEV 7   -3.0538 3.21 114.9  -0.952  0.9893
#  LEV 21 - RIF 0    2.5803 5.17  64.4   0.499  0.9999
#  LEV 21 - RIF 21   2.2803 5.11  61.6   0.447  1.0000
#  LEV 21 - RIF 7    3.0450 5.11  61.6   0.596  0.9996
#  LEV 7 - RIF 0     5.6341 5.17  64.4   1.089  0.9738
#  LEV 7 - RIF 21    5.3341 5.11  61.6   1.044  0.9797
#  LEV 7 - RIF 7     6.0988 5.11  61.6   1.194  0.9548
#  RIF 0 - RIF 21   -0.3000 3.39 113.5  -0.088  1.0000
#  RIF 0 - RIF 7     0.4647 3.39 113.5   0.137  1.0000
#  RIF 21 - RIF 7    0.7647 3.27 113.2   0.234  1.0000

fitshanntreat<- lmer(shannon~treatmentvisit+ (1|STUDY_ID), data=TreatAlphametanofever)
anova(fitshanntreat)
#                npar Sum Sq Mean Sq F value
# treatmentvisit    8 2.2221 0.27777  2.341
Tukshanntreat<-lsmeans(fitshanntreat, pairwise~treatmentvisit, adjust="tukey")
Tukshanntreat
 # contrast        estimate    SE  df t.ratio p.value
 # AZI 0 - AZI 21  -0.12746 0.115 114  -1.110  0.9716
 # AZI 0 - AZI 7   -0.09621 0.119 116  -0.811  0.9964
 # AZI 0 - LEV 0   -0.04654 0.127 104  -0.366  1.0000
 # AZI 0 - LEV 21  -0.14629 0.129 105  -1.136  0.9673
 # AZI 0 - LEV 7   -0.31475 0.129 105  -2.443  0.2722
 # AZI 0 - RIF 0    0.07979 0.134 109   0.594  0.9996
 # AZI 0 - RIF 21  -0.26848 0.131 103  -2.051  0.5119
 # AZI 0 - RIF 7   -0.26302 0.131 103  -2.010  0.5403
 # AZI 21 - AZI 7   0.03125 0.119 116   0.263  1.0000
 # AZI 21 - LEV 0   0.08093 0.127 104   0.637  0.9993
 # AZI 21 - LEV 21 -0.01883 0.129 105  -0.146  1.0000
 # AZI 21 - LEV 7  -0.18728 0.129 105  -1.454  0.8737
 # AZI 21 - RIF 0   0.20725 0.134 109   1.543  0.8326
 # AZI 21 - RIF 21 -0.14101 0.131 103  -1.077  0.9762
 # AZI 21 - RIF 7  -0.13556 0.131 103  -1.036  0.9814
 # AZI 7 - LEV 0    0.04967 0.130 109   0.381  1.0000
 # AZI 7 - LEV 21  -0.05008 0.132 110  -0.379  1.0000
 # AZI 7 - LEV 7   -0.21854 0.132 110  -1.655  0.7722
 # AZI 7 - RIF 0    0.17600 0.137 113   1.280  0.9351
 # AZI 7 - RIF 21  -0.17227 0.134 108  -1.285  0.9337
 # AZI 7 - RIF 7   -0.16681 0.134 108  -1.244  0.9446
 # LEV 0 - LEV 21  -0.09975 0.114 117  -0.876  0.9938
 # LEV 0 - LEV 7   -0.26821 0.114 117  -2.355  0.3186
 # LEV 0 - RIF 0    0.12633 0.132 116   0.959  0.9887
 # LEV 0 - RIF 21  -0.22194 0.128 110  -1.732  0.7256
 # LEV 0 - RIF 7   -0.21648 0.128 110  -1.689  0.7517
 # LEV 21 - LEV 7  -0.16845 0.115 117  -1.461  0.8708
 # LEV 21 - RIF 0   0.22608 0.133 117   1.695  0.7482
 # LEV 21 - RIF 21 -0.12218 0.130 111  -0.941  0.9900
 # LEV 21 - RIF 7  -0.11673 0.130 111  -0.899  0.9926
 # LEV 7 - RIF 0    0.39453 0.133 117   2.959  0.0857
 # LEV 7 - RIF 21   0.04627 0.130 111   0.356  1.0000
 # LEV 7 - RIF 7    0.05173 0.130 111   0.398  1.0000
 # RIF 0 - RIF 21  -0.34826 0.122 116  -2.846  0.1134
 # RIF 0 - RIF 7   -0.34281 0.122 116  -2.802  0.1262
 # RIF 21 - RIF 7   0.00546 0.118 114   0.046  1.0000

#Both cohorts baseline
baselinesampleswater<-subset(baselinesamples, TRT!='LOP' & TRT!='PLA')

ggplot(baselinesampleswater, aes(as.factor(Visit), y=richness, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Richness")+xlab("Visit")+ylab("Number of Species") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4"))+theme_pub()
ggsave(file="Analysis/230413_Metaphlan3RichnessBaselinePreventTreatTDwaternoly.pdf", height=2, width=4)

ggplot(baselinesampleswater, aes(as.factor(Visit), y=shannon, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Shannon Diversity")+xlab("Visit")+ylab("Shannon Diversity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4"))+theme_pub()
ggsave(file="Analysis/230413_Metaphlan3ShannonBaselinePreventTreatTDwaternoly.pdf", height=2, width=4)

#ANOVAS at baseline and at end of studies for richness and shannon
RichAOVbaseline<-aov(richness~TRT, data=baselinesampleswater)
TukeyHSD(RichAOVbaseline, "TRT", ordered= TRUE)

#Fit: aov(formula = richness ~ TRT, data = baselinesampleswater)
#                                                           diff        lwr      upr     p adj
# AZI-RIF                                              0.4848485 -15.956587 16.92628 0.9999994
# LEV-RIF                                              0.9523810 -14.542734 16.44750 0.9999752
# Rifaximin 550 mg daily-RIF                          29.0579710  16.290431 41.82551 0.0000000
# Rifaximin 550 mg twice a day-RIF                    31.0416667  18.077523 44.00581 0.0000000
# Placebo-RIF                                         33.7523810  20.576276 46.92849 0.0000000
# LEV-AZI                                              0.4675325 -15.402303 16.33737 0.9999994
# Rifaximin 550 mg daily-AZI                          28.5731225  15.353321 41.79292 0.0000001
# Rifaximin 550 mg twice a day-AZI                    30.5568182  17.147042 43.96659 0.0000000
# Placebo-AZI                                         33.2675325  19.652731 46.88233 0.0000000
# Rifaximin 550 mg daily-LEV                          28.1055901  16.083071 40.12811 0.0000000
# Rifaximin 550 mg twice a day-LEV                    30.0892857  17.858182 42.32039 0.0000000
# Placebo-LEV                                         32.8000000  20.344454 45.25555 0.0000000
# Rifaximin 550 mg twice a day-Rifaximin 550 mg daily  1.9836957  -6.531666 10.49906 0.9847129
# Placebo-Rifaximin 550 mg daily                       4.6944099  -4.140301 13.52912 0.6431105
# Placebo-Rifaximin 550 mg twice a day                 2.7107143  -6.405812 11.82724 0.9556730

shanAOVbaseline<-aov(shannon~TRT, data=baselinesampleswater)
TukeyHSD(shanAOVbaseline, "TRT", ordered= TRUE)
# LEV-RIF                                             0.07894248 -0.25837718 0.4162621 0.9843935
# AZI-RIF                                             0.15505220 -0.20286830 0.5129727 0.8111049
# Rifaximin 550 mg daily-RIF                          1.03332033  0.75537839 1.3112623 0.0000000
# Rifaximin 550 mg twice a day-RIF                    1.09962452  0.81740264 1.3818464 0.0000000
# Placebo-RIF                                         1.13351999  0.84668382 1.4203562 0.0000000
# AZI-LEV                                             0.07610972 -0.26936739 0.4215868 0.9881267
# Rifaximin 550 mg daily-LEV                          0.95437784  0.69265459 1.2161011 0.0000000
# Rifaximin 550 mg twice a day-LEV                    1.02068204  0.75441801 1.2869461 0.0000000
# Placebo-LEV                                         1.05457750  0.78342749 1.3257275 0.0000000
# Rifaximin 550 mg daily-AZI                          0.87826813  0.59048071 1.1660555 0.0000000
# Rifaximin 550 mg twice a day-AZI                    0.94457232  0.65264928 1.2364954 0.0000000
# Placebo-AZI                                         0.97846778  0.68208145 1.2748541 0.0000000
# Rifaximin 550 mg twice a day-Rifaximin 550 mg daily 0.06630419 -0.11907028 0.2516787 0.9063327
# Placebo-Rifaximin 550 mg daily                      0.10019966 -0.09212687 0.2925262 0.6623814
# Placebo-Rifaximin 550 mg twice a day                0.03389547 -0.16456602 0.2323570 0.9963611

endsampleswater<-subset(endsamples, TRT!='LOP' & TRT!='PLA')
ggplot(endsampleswater, aes(as.factor(Visit), y=richness, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Richness")+xlab("Visit")+ylab("Number of Species") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4"))+theme_pub()
ggsave(file="Analysis/230413_Metaphlan3RichnessendsamplesPreventTreatTDwaternoly.pdf", height=2, width=4)

ggplot(endsampleswater, aes(as.factor(Visit), y=shannon, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Shannon Diversity")+xlab("Visit")+ylab("Shannon Diversity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4"))+theme_pub()
ggsave(file="Analysis/230413_Metaphlan3ShannonendsamplesPreventTreatTDwaternoly.pdf", height=2, width=4)

RichAOVend<-aov(richness~TRT, data=endsampleswater)
TukeyHSD(RichAOVend, "TRT", ordered= TRUE)
#                                                           diff        lwr      upr     p adj
# AZI-RIF                                              1.5000000 -13.496981 16.49698 0.9997255
# LEV-RIF                                              4.1153846 -10.267122 18.49789 0.9623049
# Rifaximin 550 mg twice a day-RIF                    25.8000000  13.974815 37.62518 0.0000000
# Rifaximin 550 mg daily-RIF                          26.2173913  14.571537 37.86325 0.0000000
# Placebo-RIF                                         29.9571429  17.938618 41.97567 0.0000000
# LEV-AZI                                              2.6153846 -12.103147 17.33392 0.9956114
# Rifaximin 550 mg twice a day-AZI                    24.3000000  12.068333 36.53167 0.0000008
# Rifaximin 550 mg daily-AZI                          24.7173913  12.659009 36.77577 0.0000003
# Placebo-AZI                                         28.4571429  16.038463 40.87582 0.0000000
# Rifaximin 550 mg twice a day-LEV                    21.6846154  10.214622 33.15461 0.0000029
# Rifaximin 550 mg daily-LEV                          22.1020067  10.816987 33.38703 0.0000011
# Placebo-LEV                                         25.8417582  14.172539 37.51098 0.0000000
# Rifaximin 550 mg daily-Rifaximin 550 mg twice a day  0.4173913  -7.349857  8.18464 0.9999873
# Placebo-Rifaximin 550 mg twice a day                 4.1571429  -4.158455 12.47274 0.7006457
# Placebo-Rifaximin 550 mg daily                       3.7397516  -4.318790 11.79829 0.7624589

shannAOVend<-aov(shannon~TRT, data=endsampleswater)
TukeyHSD(shannAOVend, "TRT", ordered= TRUE)
#                                                           diff        lwr       upr     p adj
# LEV-AZI                                             0.03045318 -0.2807707 0.3416770 0.9997535
# RIF-AZI                                             0.11951849 -0.1975932 0.4366302 0.8855375
# Placebo-AZI                                         0.89368705  0.6310936 1.1562805 0.0000000
# Rifaximin 550 mg twice a day-AZI                    0.89757134  0.6389323 1.1562103 0.0000000
# Rifaximin 550 mg daily-AZI                          0.91790942  0.6629345 1.1728843 0.0000000
# RIF-LEV                                             0.08906531 -0.2150533 0.3931839 0.9584002
# Placebo-LEV                                         0.86323386  0.6164878 1.1099799 0.0000000
# Rifaximin 550 mg twice a day-LEV                    0.86711815  0.6245848 1.1096515 0.0000000
# Rifaximin 550 mg daily-LEV                          0.88745624  0.6488341 1.1260784 0.0000000
# Placebo-RIF                                         0.77416855  0.5200364 1.0283007 0.0000000
# Rifaximin 550 mg twice a day-RIF                    0.77805284  0.5280089 1.0280968 0.0000000
# Rifaximin 550 mg daily-RIF                          0.79839093  0.5521389 1.0446429 0.0000000
# Rifaximin 550 mg twice a day-Placebo                0.00388429 -0.1719493 0.1797179 0.9999998
# Rifaximin 550 mg daily-Placebo                      0.02422238 -0.1461758 0.1946205 0.9984832
# Rifaximin 550 mg daily-Rifaximin 550 mg twice a day 0.02033809 -0.1439006 0.1845768 0.9992213

#Now Shortbread to remove PLA and LOP groups
TreatShortbredmetadatawater<-subset(TreatShortbredmetadata, TRT!='LOP' & TRT!='PLA')
baselineresistancewater<-subset(baselineresistance, TRT!='LOP' & TRT!='PLA')

ggplot(baselineresistancewater, aes(as.factor(Visit), y=Sum, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Baseline resistance")+xlab("Visit")+ylab("ARG RPKM SUM") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4"))+theme_pub()+scale_y_log10()
ggsave(file="Analysis/230413_BaselineRPKMPreventTreatTDwaternoly.pdf", height=2, width=4)

ggplot(baselineresistancewater, aes(as.factor(Visit), y=Count, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Baseline resistance")+xlab("Visit")+ylab("ARG count") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4"))+theme_pub()+scale_y_log10()
ggsave(file="Analysis/230413_BaselineArgcountPreventTreatTDwaternoly.pdf", height=2, width=4)

endresistancewater<-subset(endresistance, TRT!='LOP' & TRT!='PLA')
ggplot(endresistancewater, aes(as.factor(Visit), y=Sum, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Terminal resistance")+xlab("Visit")+ylab("ARG RPKM SUM") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4"))+theme_pub()+scale_y_log10()
ggsave(file="Analysis/230413_TerminalRPKMPreventTreatTDwaternoly.pdf", height=2, width=4)

ggplot(endresistancewater, aes(as.factor(Visit), y=Count, color=TRT)) + geom_boxplot(outlier.shape = NA) +geom_point(position = position_jitterdodge(jitter.width = 0.1)) +ggtitle("Terminal resistance")+xlab("Visit")+ylab("ARG Count") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(axis.text.x = element_text(size=16), axis.title.x=element_text(size=20), axis.title.y = element_text(size=20), axis.text.y = element_text(size=16), axis.title = element_text(size=24))+scale_color_manual(values = c("Placebo" = "#E31A1C", "Rifaximin 550 mg daily" = "#1F78B4","Rifaximin 550 mg twice a day" = "#FF7F00","AZI" = "#0A4451", "LEV" = "#1B7D85","RIF" = "#8ACCC4"))+theme_pub()+scale_y_log10()
ggsave(file="Analysis/230413_EndingArgcountPreventTreatTDwaternoly.pdf", height=2, width=4)

AOVbaselineresistancewaterSum<-aov(Sum~TRT, data=baselineresistancewater)
TukeyHSD(AOVbaselineresistancewaterSum, "TRT", ordered= TRUE)
#                                                          diff        lwr      upr     p adj
# Rifaximin 550 mg twice a day-Placebo                  79.5684 -2368.9581 2528.095 0.9999990
# Rifaximin 550 mg daily-Placebo                       222.8579 -2149.9784 2595.694 0.9997986
# RIF-Placebo                                         2168.5236 -1370.3291 5707.376 0.4890137
# LEV-Placebo                                         2894.2314  -451.0928 6239.556 0.1314235
# AZI-Placebo                                         5816.6375  2159.9592 9473.316 0.0001321
# Rifaximin 550 mg daily-Rifaximin 550 mg twice a day  143.2895 -2143.7755 2430.355 0.9999728
# RIF-Rifaximin 550 mg twice a day                    2088.9552 -1392.9686 5570.879 0.5131409
# LEV-Rifaximin 550 mg twice a day                    2814.6630  -470.3801 6099.706 0.1387299
# AZI-Rifaximin 550 mg twice a day                    5737.0691  2135.4569 9338.681 0.0001286
# RIF-Rifaximin 550 mg daily                          1945.6657 -1483.4542 5374.785 0.5749768
# LEV-Rifaximin 550 mg daily                          2671.3735  -557.6477 5900.395 0.1670459
# AZI-Rifaximin 550 mg daily                          5593.7796  2043.1908 9144.368 0.0001585
# LEV-RIF                                              725.7078 -3435.9871 4887.403 0.9959860
# AZI-RIF                                             3648.1139  -767.7447 8063.972 0.1682420
# AZI-LEV                                             2922.4061 -1339.9315 7184.744 0.3591886

AOVbaselineresistancewaterCount<-aov(Count~TRT, data=baselineresistancewater)
TukeyHSD(AOVbaselineresistancewaterCount, "TRT", ordered= TRUE)
#                                                          diff        lwr       upr     p adj
# LEV-RIF                                              10.70238 -66.649525  88.05429 0.9986690
# AZI-RIF                                              60.96212 -21.113833 143.03808 0.2706716
# Rifaximin 550 mg daily-RIF                          102.32971  38.593909 166.06551 0.0001105
# Rifaximin 550 mg twice a day-RIF                    113.59167  48.874419 178.30891 0.0000170
# Placebo-RIF                                         129.33095  63.555587 195.10632 0.0000010
# AZI-LEV                                              50.25974 -28.962776 129.48226 0.4489807
# Rifaximin 550 mg daily-LEV                           91.62733  31.610689 151.64397 0.0002813
# Rifaximin 550 mg twice a day-LEV                    102.88929  41.831387 163.94718 0.0000415
# Placebo-LEV                                         118.62857  56.450251 180.80689 0.0000023
# Rifaximin 550 mg daily-AZI                           41.36759 -24.625910 107.36109 0.4628760
# Rifaximin 550 mg twice a day-AZI                     52.62955 -14.312309 119.57140 0.2131978
# Placebo-AZI                                          68.36883   0.403484 136.33418 0.0477336
# Rifaximin 550 mg twice a day-Rifaximin 550 mg daily  11.26196 -31.246888  53.77080 0.9729645
# Placebo-Rifaximin 550 mg daily                       27.00124 -17.101801  71.10429 0.4900336
# Placebo-Rifaximin 550 mg twice a day                 15.73929 -29.770585  61.24916 0.9178849

AOVendresistancewaterSum<-aov(Sum~TRT, data=endresistancewater)
TukeyHSD(AOVendresistancewaterSum, "TRT", ordered= TRUE)
#                                                           diff        lwr      upr     p adj
# Rifaximin 550 mg twice a day-Rifaximin 550 mg daily  178.66025 -1085.0522 1442.373 0.9985183
# Placebo-Rifaximin 550 mg daily                       181.56461 -1141.6489 1504.778 0.9987169
# AZI-Rifaximin 550 mg daily                          2782.10000   845.1138 4719.086 0.0007928
# LEV-Rifaximin 550 mg daily                          3040.54914  1226.6745 4854.424 0.0000474
# RIF-Rifaximin 550 mg daily                          3360.67432  1489.3679 5231.981 0.0000103
# Placebo-Rifaximin 550 mg twice a day                   2.90436 -1356.1750 1361.984 1.0000000
# AZI-Rifaximin 550 mg twice a day                    2603.43975   641.7776 4565.102 0.0025437
# LEV-Rifaximin 550 mg twice a day                    2861.88889  1021.6867 4702.091 0.0002046
# RIF-Rifaximin 550 mg twice a day                    3182.01407  1285.1770 5078.851 0.0000466
# AZI-Placebo                                         2600.53539   600.0247 4601.046 0.0033603
# LEV-Placebo                                         2858.98453   977.4243 4740.545 0.0003101
# RIF-Placebo                                         3179.10971  1242.1235 5116.096 0.0000729
# LEV-AZI                                              258.44914 -2095.5454 2612.444 0.9995654
# RIF-AZI                                              578.57433 -1819.9538 2977.102 0.9820729
# RIF-LEV                                              320.12519 -1980.1276 2620.378 0.9986264

AOVendresistancewaterCount<-aov(Count~TRT, data=endresistancewater)
TukeyHSD(AOVendresistancewaterCount, "TRT", ordered= TRUE)
#                                                            diff        lwr       upr     p adj
# AZI-RIF                                              15.7121212 -62.529624  93.95387 0.9922129
# LEV-RIF                                              24.2435897 -50.792343  99.27952 0.9373272
# Rifaximin 550 mg twice a day-RIF                    100.9871795  39.110965 162.86339 0.0000815
# Rifaximin 550 mg daily-RIF                          101.9393939  40.896006 162.98278 0.0000512
# Placebo-RIF                                         137.5303030  74.344393 200.71621 0.0000001
# LEV-AZI                                               8.5314685 -68.257561  85.32050 0.9995395
# Rifaximin 550 mg twice a day-AZI                     85.2750583  21.284200 149.26592 0.0024043
# Rifaximin 550 mg daily-AZI                           86.2272727  23.041363 149.41318 0.0017193
# Placebo-AZI                                         121.8181818  56.560055 187.07631 0.0000041
# Rifaximin 550 mg twice a day-LEV                     76.7435897  16.714844 136.77234 0.0041709
# Rifaximin 550 mg daily-LEV                           77.6958042  18.525883 136.86573 0.0029390
# Placebo-LEV                                         113.2867133  51.908838 174.66459 0.0000054
# Rifaximin 550 mg daily-Rifaximin 550 mg twice a day   0.9522145 -40.271012  42.17544 0.9999998
# Placebo-Rifaximin 550 mg twice a day                 36.5431235  -7.791043  80.87729 0.1700038
# Placebo-Rifaximin 550 mg daily                       35.5909091  -7.573285  78.75510 0.1697114
```




